"""
Quality checks. Offline. Fail loudly, exit non-zero.

Run before a snapshot may be committed, and again by the loader before it
inserts anything. A check that cannot say exactly which rows offend is not
much use, so every failure names dates and symbols.
"""

from __future__ import annotations

import csv
import datetime as dt
from dataclasses import dataclass, field
from decimal import Decimal
from pathlib import Path

from . import config, trading_calendar
from .rawio import read_json, sha256_file

MAX_LISTED = 12


@dataclass
class Report:
    passed: list[str] = field(default_factory=list)
    failures: list[str] = field(default_factory=list)

    def ok(self, name: str, detail: str = "") -> None:
        self.passed.append(f"PASS  {name}{(': ' + detail) if detail else ''}")

    def fail(self, name: str, detail: str) -> None:
        self.failures.append(f"FAIL  {name}: {detail}")

    @property
    def is_clean(self) -> bool:
        return not self.failures

    def render(self, snapshot_dir: Path) -> str:
        lines = [
            f"Snapshot check report for {snapshot_dir.name}",
            "Generated by: python -m wows_ingest check",
            "",
            *self.passed,
            *self.failures,
            "",
            f"{len(self.passed)} passed, {len(self.failures)} failed",
            "RESULT: " + ("CLEAN" if self.is_clean else "FAILED"),
            "",
        ]
        return "\n".join(lines)


def _listed(items: list[str]) -> str:
    shown = ", ".join(items[:MAX_LISTED])
    return shown if len(items) <= MAX_LISTED else f"{shown} (+{len(items) - MAX_LISTED} more)"


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def run_checks(snapshot_dir: Path) -> Report:
    report = Report()
    manifest = read_json(snapshot_dir / "manifest.json")

    # --- manifest integrity: proves nobody hand-edited a file ----------------
    mismatched = [
        name
        for name, expected in manifest["files"].items()
        if sha256_file(snapshot_dir / name) != expected
    ]
    if mismatched:
        report.fail("manifest checksums", f"files changed since build: {_listed(mismatched)}")
    else:
        report.ok("manifest checksums", f"{len(manifest['files'])} files match")

    bars = _read_csv(snapshot_dir / "bars.csv")
    instruments = _read_csv(snapshot_dir / "instruments.csv")
    calendar = [dt.date.fromisoformat(r["trade_date"]) for r in _read_csv(snapshot_dir / "calendar.csv")]
    actions = _read_csv(snapshot_dir / "corporate-actions.csv")
    excluded_rows = _read_csv(snapshot_dir / "excluded-rows.csv")
    excluded_keys = {(r["symbol"], r["trade_date"]) for r in excluded_rows}
    policy = read_json(snapshot_dir / "policy.json")

    by_symbol: dict[str, list[dict[str, str]]] = {}
    for row in bars:
        by_symbol.setdefault(row["symbol"], []).append(row)

    # --- row counts ----------------------------------------------------------
    count_problems = [
        f"{symbol}: manifest {entry['rows']}, file {len(by_symbol.get(symbol, []))}"
        for symbol, entry in manifest["per_instrument"].items()
        if entry["rows"] != len(by_symbol.get(symbol, []))
    ]
    if count_problems:
        report.fail("row counts match manifest", _listed(count_problems))
    else:
        report.ok("row counts match manifest", f"{len(bars):,} bars")

    # --- duplicates ----------------------------------------------------------
    seen: set[tuple[str, str]] = set()
    duplicates = []
    for row in bars:
        key = (row["symbol"], row["trade_date"])
        if key in seen:
            duplicates.append(f"{key[0]} {key[1]}")
        seen.add(key)
    if duplicates:
        report.fail("no duplicate (instrument, trade_date)", _listed(duplicates))
    else:
        report.ok("no duplicate (instrument, trade_date)")

    # --- prices, volume, OHLC ------------------------------------------------
    nonpositive, ohlc, negative_volume = [], [], []
    for row in bars:
        o, h, l, c = (int(row["open_paise"]), int(row["high_paise"]),
                      int(row["low_paise"]), int(row["close_paise"]))
        where = f"{row['symbol']} {row['trade_date']}"
        if min(o, h, l, c) <= 0:
            nonpositive.append(where)
        if not (l <= o <= h and l <= c <= h and l <= h):
            ohlc.append(where)
        if int(row["volume"]) < 0:
            negative_volume.append(where)
    for name, offenders in (
        ("no zero or negative prices", nonpositive),
        ("OHLC consistency (low <= open, close <= high)", ohlc),
        ("no negative volume", negative_volume),
    ):
        report.fail(name, _listed(offenders)) if offenders else report.ok(name)

    # --- calendar ------------------------------------------------------------
    covered_years = [
        y for y in range(config.FETCH_START.year, config.FETCH_END.year + 1)
        if calendar and calendar[0] <= dt.date(y, 1, 1) and dt.date(y, 12, 31) <= calendar[-1]
    ]
    calendar_problems = trading_calendar.sanity_check(calendar, covered_years)
    if calendar_problems:
        report.fail("trading calendar is plausible", _listed(calendar_problems))
    else:
        report.ok(
            "trading calendar is plausible",
            f"{len(calendar):,} days from {calendar[0]} to {calendar[-1]}, "
            f"{len(covered_years)} full years in range",
        )

    # --- gaps, both directions ----------------------------------------------
    trading_days = set(calendar)
    illiquid = {i["symbol"]: i for i in policy.get("illiquid_instruments", [])}
    known_gaps: dict[str, set[str]] = {}
    for entry in policy.get("known_source_gaps", []):
        known_gaps.setdefault(entry["symbol"], set()).update(entry["dates"])
    missing_report, off_calendar_report, tolerance_report, outside_report = [], [], [], []
    for symbol, rows in sorted(by_symbol.items()):
        days = {dt.date.fromisoformat(r["trade_date"]) for r in rows}
        first, last = min(days), max(days)
        expected = {d for d in trading_days if first <= d <= last}
        # A gap is only a failure if nothing explains it. Rows removed as a
        # recorded source defect or as structurally impossible are explained,
        # and excluded-rows.csv says which and why.
        missing = sorted(
            d
            for d in (expected - days)
            if (symbol, d.isoformat()) not in excluded_keys
            and d.isoformat() not in known_gaps.get(symbol, set())
        )
        off = sorted(days - trading_days)
        if symbol in illiquid:
            # The instrument genuinely does not trade every day. That is
            # allowed, but only up to a stated fraction, so a series that
            # quietly gets worse still fails.
            allowed = Decimal(str(illiquid[symbol]["max_missing_fraction"]))
            actual = Decimal(len(missing)) / Decimal(len(expected) or 1)
            if actual > allowed:
                tolerance_report.append(
                    f"{symbol}: {len(missing)} of {len(expected)} days missing "
                    f"({actual:.3f}), above the recorded tolerance of {allowed}"
                )
            missing = []
        # Scoped the same way as the discontinuity check, and for the same
        # reason: the snapshot deliberately reaches back well before any
        # scenario, and a hole in 2008 must not fail a build over a 2019-2023
        # universe. When a future scenario adopts an earlier window, these
        # become failures and have to be explained then.
        in_window = [d for d in missing if config.SCENARIO_WINDOW_START <= d <= config.SCENARIO_WINDOW_END]
        out_window = [d for d in missing if d not in set(in_window)]
        if out_window:
            outside_report.append(f"{symbol}: {len(out_window)}")
        if in_window:
            missing_report.append(f"{symbol}: {_listed([d.isoformat() for d in in_window])}")
        if off:
            off_calendar_report.append(f"{symbol}: {_listed([d.isoformat() for d in off])}")
    if missing_report:
        report.fail(
            "no gaps inside a scenario window", "; ".join(missing_report[:6])
        )
    else:
        report.ok("no gaps inside a scenario window", f"{len(calendar):,} trading days checked")
    report.ok(
        "gaps outside every scenario window (recorded, not fatal)",
        ", ".join(sorted(outside_report)) if outside_report else "none",
    )
    if off_calendar_report:
        report.fail("every bar falls on a trading day", "; ".join(off_calendar_report[:6]))
    else:
        report.ok("every bar falls on a trading day")
    if tolerance_report:
        report.fail("illiquid instruments stay within their recorded tolerance", _listed(tolerance_report))
    elif illiquid:
        report.ok(
            "illiquid instruments stay within their recorded tolerance",
            ", ".join(sorted(illiquid)),
        )

    # --- every removal is accounted for --------------------------------------
    unexplained = [
        f"{r['symbol']} {r['trade_date']}" for r in excluded_rows if not r["reason"].strip()
    ]
    if unexplained:
        report.fail("every excluded row states a reason", _listed(unexplained))
    else:
        report.ok(
            "every excluded row states a reason",
            f"{len(excluded_rows)} rows removed, each with a recorded reason",
        )

    # --- excluded rows inside a scenario window are visible -------------------
    in_window_exclusions = sorted(
        f"{r['symbol']} {r['trade_date']}"
        for r in excluded_rows
        if config.SCENARIO_WINDOW_START
        <= dt.date.fromisoformat(r["trade_date"])
        <= config.SCENARIO_WINDOW_END
    )
    report.ok(
        "exclusions inside a scenario window",
        _listed(in_window_exclusions) if in_window_exclusions else "none",
    )

    # --- corporate actions inside a scenario window --------------------------
    offending = [
        f"{a['symbol']} {a['event_date']} {a['ratio']}"
        for a in actions
        if a["in_scenario_window"] == "true"
    ]
    if offending:
        report.fail(
            "no split or bonus inside a scenario window",
            f"the universe admits only unaffected instruments: {_listed(offending)}",
        )
    else:
        report.ok(
            "no split or bonus inside a scenario window",
            f"{len(actions)} events found, all outside",
        )

    # --- discontinuity band, scoped to the window ----------------------------
    band = policy["discontinuity_band"]
    low, high = Decimal(str(band["min_ratio"])), Decimal(str(band["max_ratio"]))
    exempt = {(e["symbol"], e["date"]) for e in policy.get("exceptions", [])}
    jumps = []
    for symbol, rows in sorted(by_symbol.items()):
        ordered = sorted(rows, key=lambda r: r["trade_date"])
        for previous, current in zip(ordered, ordered[1:]):
            day = dt.date.fromisoformat(current["trade_date"])
            if not (config.SCENARIO_WINDOW_START <= day <= config.SCENARIO_WINDOW_END):
                continue
            before = Decimal(previous["close_paise"])
            if before == 0:
                continue
            ratio = Decimal(current["close_paise"]) / before
            if (ratio < low or ratio > high) and (symbol, current["trade_date"]) not in exempt:
                jumps.append(f"{symbol} {current['trade_date']} ratio {ratio:.3f}")
    if jumps:
        report.fail(
            "no unexplained price discontinuity in window",
            f"outside {low}-{high}: {_listed(jumps)}",
        )
    else:
        report.ok("no unexplained price discontinuity in window", f"band {low}-{high}")

    # --- scenario window coverage -------------------------------------------
    uncovered = []
    for window in manifest["scenario_windows"]:
        start, end = dt.date.fromisoformat(window["start"]), dt.date.fromisoformat(window["end"])
        for inst in config.all_instruments():
            if inst.symbol == config.CASH_INSTRUMENT.symbol:
                continue
            rows = by_symbol.get(inst.symbol, [])
            if not rows:
                uncovered.append(f"{inst.symbol}: no bars at all")
                continue
            days = [dt.date.fromisoformat(r["trade_date"]) for r in rows]
            if min(days) > start or max(days) < end:
                uncovered.append(
                    f"{inst.symbol}: has {min(days)}..{max(days)}, "
                    f"window {window['name']} needs {start}..{end}"
                )
    if uncovered:
        report.fail("every instrument covers every scenario window", _listed(uncovered))
    else:
        report.ok("every instrument covers every scenario window")

    # --- cash carries no bars ------------------------------------------------
    if by_symbol.get(config.CASH_INSTRUMENT.symbol):
        report.fail("cash has no bars", f"{config.CASH_INSTRUMENT.symbol} has bars")
    else:
        report.ok("cash has no bars")

    # --- instruments file matches config ------------------------------------
    file_symbols = {r["symbol"] for r in instruments}
    config_symbols = {i.symbol for i in config.all_instruments()}
    if file_symbols != config_symbols:
        report.fail(
            "instruments.csv matches the configured universe",
            f"only in file: {_listed(sorted(file_symbols - config_symbols))}; "
            f"only in config: {_listed(sorted(config_symbols - file_symbols))}",
        )
    else:
        report.ok("instruments.csv matches the configured universe", f"{len(file_symbols)} instruments")

    # --- provenance of the deposit series -----------------------------------
    if not manifest.get("fd_series_verified", False):
        report.ok(
            "deposit-rate series provenance",
            "UNVERIFIED and recorded as such in the manifest; see docs/DATA.md before "
            "a real season uses the fixed deposit",
        )
    return report
