// GENERATED by scripts/generate-types.ts — do not edit. Run `npm run db:generate-types`.
import type { InferInsertModel, InferSelectModel } from "drizzle-orm";
import type * as schema from "./schema";

export type ApplicationsRow = InferSelectModel<typeof schema.applications>;
export type ApplicationsInsert = InferInsertModel<typeof schema.applications>;
export type AttendanceRow = InferSelectModel<typeof schema.attendance>;
export type AttendanceInsert = InferInsertModel<typeof schema.attendance>;
export type AuditLogRow = InferSelectModel<typeof schema.auditLog>;
export type AuditLogInsert = InferInsertModel<typeof schema.auditLog>;
export type EventsRow = InferSelectModel<typeof schema.events>;
export type EventsInsert = InferInsertModel<typeof schema.events>;
export type FillsRow = InferSelectModel<typeof schema.fills>;
export type FillsInsert = InferInsertModel<typeof schema.fills>;
export type ForecastQuestionsRow = InferSelectModel<
  typeof schema.forecastQuestions
>;
export type ForecastQuestionsInsert = InferInsertModel<
  typeof schema.forecastQuestions
>;
export type ForecastsRow = InferSelectModel<typeof schema.forecasts>;
export type ForecastsInsert = InferInsertModel<typeof schema.forecasts>;
export type GameInstancesRow = InferSelectModel<typeof schema.gameInstances>;
export type GameInstancesInsert = InferInsertModel<typeof schema.gameInstances>;
export type HoldingsCacheRow = InferSelectModel<typeof schema.holdingsCache>;
export type HoldingsCacheInsert = InferInsertModel<typeof schema.holdingsCache>;
export type InstrumentsRow = InferSelectModel<typeof schema.instruments>;
export type InstrumentsInsert = InferInsertModel<typeof schema.instruments>;
export type MembershipsRow = InferSelectModel<typeof schema.memberships>;
export type MembershipsInsert = InferInsertModel<typeof schema.memberships>;
export type ModulesRow = InferSelectModel<typeof schema.modules>;
export type ModulesInsert = InferInsertModel<typeof schema.modules>;
export type OrdersRow = InferSelectModel<typeof schema.orders>;
export type OrdersInsert = InferInsertModel<typeof schema.orders>;
export type PositionsRow = InferSelectModel<typeof schema.positions>;
export type PositionsInsert = InferInsertModel<typeof schema.positions>;
export type PriceBarsRow = InferSelectModel<typeof schema.priceBars>;
export type PriceBarsInsert = InferInsertModel<typeof schema.priceBars>;
export type ProgressRow = InferSelectModel<typeof schema.progress>;
export type ProgressInsert = InferInsertModel<typeof schema.progress>;
export type RateLimitsRow = InferSelectModel<typeof schema.rateLimits>;
export type RateLimitsInsert = InferInsertModel<typeof schema.rateLimits>;
export type ResearchNotesRow = InferSelectModel<typeof schema.researchNotes>;
export type ResearchNotesInsert = InferInsertModel<typeof schema.researchNotes>;
export type ReviewsRow = InferSelectModel<typeof schema.reviews>;
export type ReviewsInsert = InferInsertModel<typeof schema.reviews>;
export type RsvpsRow = InferSelectModel<typeof schema.rsvps>;
export type RsvpsInsert = InferInsertModel<typeof schema.rsvps>;
export type RunLedgerEntriesRow = InferSelectModel<
  typeof schema.runLedgerEntries
>;
export type RunLedgerEntriesInsert = InferInsertModel<
  typeof schema.runLedgerEntries
>;
export type RunsRow = InferSelectModel<typeof schema.runs>;
export type RunsInsert = InferInsertModel<typeof schema.runs>;
export type ScenariosRow = InferSelectModel<typeof schema.scenarios>;
export type ScenariosInsert = InferInsertModel<typeof schema.scenarios>;
export type ScoresRow = InferSelectModel<typeof schema.scores>;
export type ScoresInsert = InferInsertModel<typeof schema.scores>;
export type SeasonsRow = InferSelectModel<typeof schema.seasons>;
export type SeasonsInsert = InferInsertModel<typeof schema.seasons>;
export type SnapshotsRow = InferSelectModel<typeof schema.snapshots>;
export type SnapshotsInsert = InferInsertModel<typeof schema.snapshots>;
export type ThesesRow = InferSelectModel<typeof schema.theses>;
export type ThesesInsert = InferInsertModel<typeof schema.theses>;
export type TracksRow = InferSelectModel<typeof schema.tracks>;
export type TracksInsert = InferInsertModel<typeof schema.tracks>;
export type UserRolesRow = InferSelectModel<typeof schema.userRoles>;
export type UserRolesInsert = InferInsertModel<typeof schema.userRoles>;
export type UsersRow = InferSelectModel<typeof schema.users>;
export type UsersInsert = InferInsertModel<typeof schema.users>;
export type VerticalsRow = InferSelectModel<typeof schema.verticals>;
export type VerticalsInsert = InferInsertModel<typeof schema.verticals>;
