/**
 * npm run db:generate-types — writes src/db/types.ts with a select/insert
 * type for every table in src/db/schema.ts. The types are inferred by
 * Drizzle from the schema, so this file is derived, never hand-edited; CI
 * regenerates it and fails if the committed copy differs.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { isTable } from "drizzle-orm";
import * as schema from "@/db/schema";

const pascal = (s: string) =>
  s.replace(/(^|_)([a-z])/g, (_, __, c: string) => c.toUpperCase());

const lines = [
  "// GENERATED by scripts/generate-types.ts — do not edit. Run `npm run db:generate-types`.",
  'import type { InferInsertModel, InferSelectModel } from "drizzle-orm";',
  'import type * as schema from "./schema";',
  "",
];
for (const [name, value] of Object.entries(schema)) {
  if (!isTable(value)) continue;
  const base = pascal(name);
  lines.push(
    `export type ${base}Row = InferSelectModel<typeof schema.${name}>;`,
  );
  lines.push(
    `export type ${base}Insert = InferInsertModel<typeof schema.${name}>;`,
  );
}
lines.push("");
writeFileSync(resolve(process.cwd(), "src/db/types.ts"), lines.join("\n"));
console.log("wrote src/db/types.ts");
